### ISSUE TITLE
Script Instantiation

### ISSUE THREAD

**Issue by marklundin** [playcanvas/web-components#43]
Could we provide an alternative way of instantiating scripts here?

Current way
```html
<script type="module">
    import { registerScript } from 'playcanvas';
    import { OrbitCamera } from './scripts/orbit-camera.mjs';

    const app = document.querySelector('pc-app');
    await app.getApplication();
    registerScript(OrbitCamera, 'orbitCamera');
</script>
<pc-script name="OrbitCamera"></pc-script>
```

Instead we could dynamically import the Module within `pc-script` 

```javascript
// in pc-script.js
const src = node.getAttribute('name');
const { default } = await import(new URL(src, window.location.origin + window.location.pathname)
this.component.create(default);

// in html
<pc-script src='./scripts/orbit-camera.mjs' />
```

This would resolve it relative to the html which is the same as plain `<script>` tags.

The caveat here, is that it would only work with ESM Scripts. Additionally, modules can export multiple `Script`'s. So you'd need to iterate over all of them, but that may not be desirable. Or alternatively, filter exports via an optional comma delimited query string param... 
```html
<pc-script src='./scripts/orbit-camera.mjs?only=orbitCameraInputMouse'  />
```

**Comment by willeastcott** [comment]
Yes, the way scripts are currently imported is a bit ugly at the moment. However, your suggestion here doesn't quite feel right to me because many script components sprinkled around the hierarchy might use the same scripts. So it feels like I should be importing a script once and then assigning that imported scripts somehow is a better way to go. But with web components/HTML, I can't pass the script class...I can only pass a string. Which means I need to register the script externally. 

Alternatively, I could list scripts as assets. This _almost_ works, but throws an exception here:

https://github.com/playcanvas/engine/blob/641ee34bb79c5ab4b01a11b48b8dd93c2c3f3b2e/src/framework/handlers/script.js#L156

**Comment by willeastcott** [comment]
For now, I'm going to go with loading scripts as assets which works fine. Longer term, it would be nice to figure out how to 'build' a Web Components app. But for now, I think we have a good enough script system to launch with.
